"""remove_recruiters_table_and_fk

Revision ID: 050c9515c534
Revises: 7c7e128e24de
Create Date: 2025-12-19 17:26:43.242974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '050c9515c534'
down_revision: Union[str, None] = '7c7e128e24de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # IMPORTANT: Drop FK constraint BEFORE dropping the table
    op.drop_constraint('recruiter_tasks_assigned_to_fkey', 'recruiter_tasks', type_='foreignkey')
    op.create_index(op.f('ix_recruiter_tasks_assigned_to'), 'recruiter_tasks', ['assigned_to'], unique=False)
    op.drop_table('recruiters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('recruiter_tasks_assigned_to_fkey'), 'recruiter_tasks', 'recruiters', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_recruiter_tasks_assigned_to'), table_name='recruiter_tasks')
    op.create_table('recruiters',
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='ФИО рекрутера'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Дата создания'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Дата последнего обновления'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Ory Identity ID рекрутера'),
    sa.PrimaryKeyConstraint('id', name=op.f('recruiters_pkey'))
    )
    # ### end Alembic commands ###
