"""add recruiters and tasks tables

Revision ID: 32e3353aea89
Revises: 567159bb0f22
Create Date: 2025-12-19 09:36:20.778683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32e3353aea89'
down_revision: Union[str, None] = '567159bb0f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID рекрутера'),
    sa.Column('full_name', sa.String(length=200), nullable=False, comment='ФИО рекрутера'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID типа задачи'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Код типа задачи (vacancy_approval, send_offer, etc.)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Название типа задачи'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание типа задачи'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен ли тип задачи'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последнего обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_types_code'), 'task_types', ['code'], unique=True)
    op.create_table('recruiter_tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID задачи'),
    sa.Column('task_type_id', sa.Integer(), nullable=False, comment='ID типа задачи'),
    sa.Column('status', sa.Enum('POOL', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='task_status'), nullable=False, comment='Статус задачи: POOL, IN_PROGRESS, COMPLETED, REJECTED'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='ID рекрутера, которому назначена задача (NULL = общий пул)'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Контекст задачи в формате JSON (например, {vacancy_id: 123})'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Заголовок задачи'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание задачи'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания задачи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата последнего обновления'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата завершения задачи'),
    sa.Column('created_by_type', sa.String(length=50), nullable=True, comment='Тип создателя: hiring_manager, system, candidate'),
    sa.Column('created_by_id', sa.String(length=100), nullable=True, comment='ID создателя задачи'),
    sa.ForeignKeyConstraint(['assigned_to'], ['recruiters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_tasks_assigned_to'), 'recruiter_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_recruiter_tasks_id'), 'recruiter_tasks', ['id'], unique=True)
    op.create_index(op.f('ix_recruiter_tasks_status'), 'recruiter_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_recruiter_tasks_task_type_id'), 'recruiter_tasks', ['task_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiter_tasks_task_type_id'), table_name='recruiter_tasks')
    op.drop_index(op.f('ix_recruiter_tasks_status'), table_name='recruiter_tasks')
    op.drop_index(op.f('ix_recruiter_tasks_id'), table_name='recruiter_tasks')
    op.drop_index(op.f('ix_recruiter_tasks_assigned_to'), table_name='recruiter_tasks')
    op.drop_table('recruiter_tasks')
    op.drop_index(op.f('ix_task_types_code'), table_name='task_types')
    op.drop_table('task_types')
    op.drop_table('recruiters')
    # ### end Alembic commands ###
