"""add quiz tables

Revision ID: 567159bb0f22
Revises: abc123def456
Create Date: 2025-12-19 08:20:45.107674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567159bb0f22'
down_revision: Union[str, None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный ID блока'),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Название блока (например, 'Algorithms', 'Python Basics')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание блока'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Блок активен и используется'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Когда блок был создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Когда блок последний раз обновлялся'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID вопроса'),
    sa.Column('block_id', sa.Integer(), nullable=False, comment='Ссылка на блок'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='Текст вопроса'),
    sa.Column('option_a', sa.Text(), nullable=False, comment='Вариант ответа A'),
    sa.Column('option_b', sa.Text(), nullable=False, comment='Вариант ответа B'),
    sa.Column('option_c', sa.Text(), nullable=False, comment='Вариант ответа C'),
    sa.Column('option_d', sa.Text(), nullable=False, comment='Вариант ответа D'),
    sa.Column('correct_answer', sa.String(length=1), nullable=False, comment='Правильный ответ (A, B, C, или D)'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='Уровень сложности (easy, medium, hard)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Вопрос активен и используется'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Когда вопрос был создан'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Когда вопрос последний раз обновлялся'),
    sa.CheckConstraint("correct_answer IN ('A', 'B', 'C', 'D')", name='ck_correct_answer_valid'),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_difficulty_valid'),
    sa.ForeignKeyConstraint(['block_id'], ['quiz_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_block_active', 'quiz_questions', ['block_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_quiz_questions_block_id'), 'quiz_questions', ['block_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=True)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID сессии'),
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Ссылка на кандидата'),
    sa.Column('track_id', sa.Integer(), nullable=False, comment='Ссылка на трек'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус: in_progress, completed, expired'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Когда квиз был начат'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Когда квиз истекает (started_at + 15 минут)'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='Когда квиз был завершен'),
    sa.Column('total_questions', sa.Integer(), nullable=False, comment='Всего вопросов отвечено'),
    sa.Column('correct_answers', sa.Integer(), nullable=False, comment='Количество правильных ответов'),
    sa.Column('wrong_answers', sa.Integer(), nullable=False, comment='Количество неправильных ответов'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Итоговый счет (процент правильных ответов)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Когда сессия была создана'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Когда сессия последний раз обновлялась'),
    sa.CheckConstraint("status IN ('in_progress', 'completed', 'expired')", name='ck_status_valid'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_candidate', 'quiz_sessions', ['candidate_id'], unique=False)
    op.create_index('idx_status', 'quiz_sessions', ['status'], unique=False)
    op.create_index('idx_track', 'quiz_sessions', ['track_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_candidate_id'), 'quiz_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_id'), 'quiz_sessions', ['id'], unique=True)
    op.create_index(op.f('ix_quiz_sessions_status'), 'quiz_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_track_id'), 'quiz_sessions', ['track_id'], unique=False)
    op.create_table('track_quiz_blocks',
    sa.Column('track_id', sa.Integer(), nullable=False, comment='Ссылка на трек'),
    sa.Column('block_id', sa.Integer(), nullable=False, comment='Ссылка на блок квиза'),
    sa.Column('questions_count', sa.Integer(), nullable=False, comment='Сколько вопросов из этого блока в квизе'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Когда связь была создана'),
    sa.ForeignKeyConstraint(['block_id'], ['quiz_blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'block_id')
    )
    op.create_table('quiz_answers',
    sa.Column('id', sa.UUID(), nullable=False, comment='Уникальный UUID ответа'),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Ссылка на сессию квиза'),
    sa.Column('question_id', sa.UUID(), nullable=False, comment='Ссылка на вопрос'),
    sa.Column('candidate_answer', sa.String(length=1), nullable=False, comment='Ответ кандидата (A, B, C, или D)'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='Правильный ли ответ'),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False, comment='Когда был дан ответ'),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True, comment='Сколько времени потрачено на ответ (в секундах)'),
    sa.CheckConstraint("candidate_answer IN ('A', 'B', 'C', 'D')", name='ck_candidate_answer_valid'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_session_question')
    )
    op.create_index('idx_session', 'quiz_answers', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_id'), 'quiz_answers', ['id'], unique=True)
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_session_id'), 'quiz_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_session_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_id'), table_name='quiz_answers')
    op.drop_index('idx_session', table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_table('track_quiz_blocks')
    op.drop_index(op.f('ix_quiz_sessions_track_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_status'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_candidate_id'), table_name='quiz_sessions')
    op.drop_index('idx_track', table_name='quiz_sessions')
    op.drop_index('idx_status', table_name='quiz_sessions')
    op.drop_index('idx_candidate', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_block_id'), table_name='quiz_questions')
    op.drop_index('idx_block_active', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_table('quiz_blocks')
    # ### end Alembic commands ###
