"""refractor candidte model

Revision ID: 5b9ac8c99608
Revises: f8ea086239ff
Create Date: 2025-12-19 12:24:27.140937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b9ac8c99608'
down_revision: Union[str, None] = 'f8ea086239ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username'))
    op.add_column('candidates', sa.Column('surname', sa.String(length=255), nullable=False, comment='Фамилия кандидата'))
    op.add_column('candidates', sa.Column('name', sa.String(length=255), nullable=False, comment='Имя кандидата'))
    op.add_column('candidates', sa.Column('email', sa.String(length=255), nullable=True, comment='Email адрес'))
    op.add_column('candidates', sa.Column('resume_link', sa.String(length=500), nullable=True, comment='Ссылка на резюме (PDF)'))
    op.add_column('candidates', sa.Column('priority1', sa.String(length=100), nullable=True, comment='Первый приоритет трека (название)'))
    op.add_column('candidates', sa.Column('priority2', sa.String(length=100), nullable=True, comment='Второй приоритет трека (название)'))
    op.add_column('candidates', sa.Column('specialty', sa.String(length=255), nullable=True, comment='Специальность'))
    op.add_column('candidates', sa.Column('employment_hours', sa.String(length=50), nullable=True, comment='Количество часов для работы'))
    op.add_column('candidates', sa.Column('city', sa.String(length=255), nullable=True, comment='Город'))
    op.add_column('candidates', sa.Column('source', sa.String(length=100), nullable=True, comment='Источник (откуда узнал о стажировке)'))
    op.add_column('candidates', sa.Column('birth_year', sa.String(length=10), nullable=True, comment='Год рождения'))
    op.add_column('candidates', sa.Column('citizenship', sa.String(length=100), nullable=True, comment='Гражданство'))
    op.add_column('candidates', sa.Column('tech_stack', sa.String(length=500), nullable=True, comment='Технологический стек'))
    op.alter_column('candidates', 'course',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               comment="Курс обучения (например '4 курс')",
               existing_comment='Курс обучения (1-6)',
               existing_nullable=True)
    op.drop_column('candidates', 'preferred_tracks')
    op.drop_column('candidates', 'achievements')
    op.drop_column('candidates', 'location')
    op.drop_column('candidates', 'domains')
    op.drop_column('candidates', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Полное имя кандидата'))
    op.add_column('candidates', sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False, comment='Области интересов/доменов (ML, Web, Mobile, etc.)'))
    op.add_column('candidates', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Местоположение (город, страна)'))
    op.add_column('candidates', sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False, comment='Достижения кандидата (олимпиады, проекты, etc.)'))
    op.add_column('candidates', sa.Column('preferred_tracks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='Список ID треков в порядке приоритета'))
    op.alter_column('candidates', 'course',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               comment='Курс обучения (1-6)',
               existing_comment="Курс обучения (например '4 курс')",
               existing_nullable=True)
    op.drop_column('candidates', 'tech_stack')
    op.drop_column('candidates', 'citizenship')
    op.drop_column('candidates', 'birth_year')
    op.drop_column('candidates', 'source')
    op.drop_column('candidates', 'city')
    op.drop_column('candidates', 'employment_hours')
    op.drop_column('candidates', 'specialty')
    op.drop_column('candidates', 'priority2')
    op.drop_column('candidates', 'priority1')
    op.drop_column('candidates', 'resume_link')
    op.drop_column('candidates', 'email')
    op.drop_column('candidates', 'name')
    op.drop_column('candidates', 'surname')
    op.drop_column('candidates', 'username')
    # ### end Alembic commands ###
