"""change recruiter id to uuid and task status backlog

Revision ID: 7c7e128e24de
Revises: 5b9ac8c99608
Create Date: 2025-12-19 13:22:55.385444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c7e128e24de'
down_revision: Union[str, None] = '5b9ac8c99608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recruiter_tasks', 'status',
               existing_type=postgresql.ENUM('POOL', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='task_status'),
               comment='Статус задачи: BACKLOG, IN_PROGRESS, COMPLETED, REJECTED',
               existing_comment='Статус задачи: POOL, IN_PROGRESS, COMPLETED, REJECTED',
               existing_nullable=False)
    op.alter_column('recruiter_tasks', 'assigned_to',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='Ory Identity ID рекрутера, которому назначена задача (NULL = backlog)',
               existing_comment='ID рекрутера, которому назначена задача (NULL = общий пул)',
               existing_nullable=True)
    op.alter_column('recruiters', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               comment='Ory Identity ID рекрутера',
               existing_comment='Уникальный ID рекрутера',
               existing_nullable=False,
               existing_server_default=sa.text("nextval('recruiters_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recruiters', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='Уникальный ID рекрутера',
               existing_comment='Ory Identity ID рекрутера',
               existing_nullable=False,
               existing_server_default=sa.text("nextval('recruiters_id_seq'::regclass)"))
    op.alter_column('recruiter_tasks', 'assigned_to',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               comment='ID рекрутера, которому назначена задача (NULL = общий пул)',
               existing_comment='Ory Identity ID рекрутера, которому назначена задача (NULL = backlog)',
               existing_nullable=True)
    op.alter_column('recruiter_tasks', 'status',
               existing_type=postgresql.ENUM('POOL', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='task_status'),
               comment='Статус задачи: POOL, IN_PROGRESS, COMPLETED, REJECTED',
               existing_comment='Статус задачи: BACKLOG, IN_PROGRESS, COMPLETED, REJECTED',
               existing_nullable=False)
    # ### end Alembic commands ###
