"""add quiz tables

Revision ID: ded7efbf5559
Revises: abc123def456
Create Date: 2025-12-18 22:32:24.667727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded7efbf5559'
down_revision: Union[str, None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interview_feedbacks_pool_id_key'), 'interview_feedbacks', type_='unique')
    op.drop_index(op.f('ix_interview_feedbacks_pool_id'), table_name='interview_feedbacks')
    op.create_index(op.f('ix_interview_feedbacks_pool_id'), 'interview_feedbacks', ['pool_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_feedbacks_pool_id'), table_name='interview_feedbacks')
    op.create_index(op.f('ix_interview_feedbacks_pool_id'), 'interview_feedbacks', ['pool_id'], unique=False)
    op.create_unique_constraint(op.f('interview_feedbacks_pool_id_key'), 'interview_feedbacks', ['pool_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
