"""remove audit field from rectuiter_task

Revision ID: f8ea086239ff
Revises: 32e3353aea89
Create Date: 2025-12-19 09:55:28.912414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ea086239ff'
down_revision: Union[str, None] = '32e3353aea89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter_tasks', 'created_by_type')
    op.drop_column('recruiter_tasks', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiter_tasks', sa.Column('created_by_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='ID создателя задачи'))
    op.add_column('recruiter_tasks', sa.Column('created_by_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='Тип создателя: hiring_manager, system, candidate'))
    # ### end Alembic commands ###
